BATCH_SIZE = 8
PRECISION = 16
GRADIENT_ACCUMULATION_BATCHES = 32
IMAGE_SIZE = 256
TRAIN_SIZE = 0.7
VALID_SIZE = 0.2
TEST_SIZE = 0.1
BASE_CHANNEL_SIZE = 16
LATENT_DIM = 128
NUM_INPUT_CHANNELS = 2
EPOCHS = 100
LEARNING_RATE = 1e-1
LEARNING_RATE_DECAY = 1e-4
T_0 = 5
T_mult = 1
EARLY_STOPPING_PATIENCE = 10
EARLY_STOPPING_MIN_DELTA = 0.0
OVERFIT_BATCHES = 0
CROP_SIZE_SECONDS = 30
SEED = 24
GRADIENT_CLIP_VAL = 1.0
GRADIENT_CLIP_TYPE = "norm"