BATCH_SIZE = 8
PRECISION = 16
PRECISION_INFERENCE = 32
GRADIENT_ACCUMULATION_BATCHES = 4
INPUT_SIZE = 256
TRAIN_SIZE = 0.7
VALID_SIZE = 0.2
TEST_SIZE = 0.1
BASE_CHANNEL_SIZE = 32
LATENT_DIM = 128
NUM_INPUT_CHANNELS = 2
EPOCHS = 100
LEARNING_RATE = 1e-3
LEARNING_RATE_DECAY = 1e-2
T_0 = 5
T_mult = 1
EARLY_STOPPING_PATIENCE = 10
EARLY_STOPPING_MIN_DELTA = 0.0
OVERFIT_BATCHES = 1
SAMPLE_RATE = 48000
CROP_SIZE_SECONDS = 30
SEED = 24
GRADIENT_CLIP_VAL = 1.0
GRADIENT_CLIP_TYPE = "norm"
N_FFT=2048
WIN_LENGTH=1024
HOP_LENGTH=1024
N_MELS=256