title = "spotify-playlist-generator"

[mongodb]
host = "127.0.0.1"
port = 27017
user = ""
password = ""
db_name = "spotify-playlist"
playlist_collection = "playlist"
song_collection = "song"
counter_collection = "counter"

[postgresql]
host = ""
port = ""
user = ""
password = ""
db_name = ""


[rabbitmq]
host = ""
port = ""
playlist_queue = "playlist"
song_queue = "song"
counter_queue = "counter"

[model]
path = "data/models/torchscript_model.pt"
k = 5
